# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink: /blog/:year/:month/:day/:title

# Setup
title:            Isaac's Blog
tagline:          'A Jekyll theme'
description:      'Simple blog posts about me learning HTML,CSS,and JavaScript. Mainly will be posting weekly in a technical blog form.'
url:              https://github.com/jacob319
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:          https://github.com/jacob319
